### ISSUE TITLE
the version of your labview

### ISSUE THREAD

**Issue by GuQian-Alex** [sw4sys/lv-tcp-socket#1]
Hello, my labview2019 cannot open your program. Can you tell me the version you use?

**Comment by jakub-uli** [comment]
Hi Alex!
The LabVIEW version that I was using writing this library was 2021 (32-bit).
If you cannot use LV2021 I can make an export to 2019 and upload.
I've also did quick fix and made a v.1.0.0 release.

**Comment by GuQian-Alex** [comment]
Thank you for you help, I have just changed my LV to 2021. Your work is so good, looking forward to its  release.^_^

**Comment by jakub-uli** [comment]
Thanks! You're welcome! Here is a link to v1.0.0 release -> https://github.com/jakub-uli/lv-tcp-socket/releases/tag/v1.0.0
Thanks for your comment, otherwise I wouldn't make a fix and later the release 😄
